"""empty message

Revision ID: 9143e822cc0c
Revises: 87fa90b64b35
Create Date: 2023-04-04 18:05:00.075570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9143e822cc0c'
down_revision = '87fa90b64b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_column('length_ref')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length_ref', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
