"""empty message

Revision ID: cd1e4b08bd8e
Revises: 9143e822cc0c
Create Date: 2023-07-07 18:59:02.197598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1e4b08bd8e'
down_revision = '9143e822cc0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clean_empty', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('convert_to_utf', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_column('convert_to_utf')
        batch_op.drop_column('clean_empty')

    # ### end Alembic commands ###
