"""empty message

Revision ID: d08a9f39b86d
Revises: 
Create Date: 2023-03-23 22:51:41.608288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08a9f39b86d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_entry', sa.TIMESTAMP(), nullable=False),
    sa.Column('set_limit', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_last_entry'), ['last_entry'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)

    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('length_ref', sa.Boolean(), nullable=True),
    sa.Column('use_coma_sep', sa.Boolean(), nullable=True),
    sa.Column('expect_feet', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_name'], ['user.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setting_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_setting_public'), ['public'], unique=False)

    op.create_table('thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ident', sa.Integer(), nullable=True),
    sa.Column('waits', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thread_ident'), ['ident'], unique=True)

    op.create_table('fandom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('separation', sa.Integer(), nullable=True),
    sa.Column('support_value_1', sa.Boolean(), nullable=True),
    sa.Column('support_value_2', sa.Boolean(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fandom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fandom_name'), ['name'], unique=False)

    op.create_table('image_conv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_id', sa.Integer(), nullable=True),
    sa.Column('phrase', sa.String(length=64), nullable=False),
    sa.Column('separation', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.String(length=64), nullable=False),
    sa.Column('mutations', sa.Boolean(), nullable=True),
    sa.Column('images', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase_conv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_id', sa.Integer(), nullable=True),
    sa.Column('direct', sa.Boolean(), nullable=True),
    sa.Column('mutations', sa.Boolean(), nullable=True),
    sa.Column('phrase_from', sa.String(length=64), nullable=False),
    sa.Column('phrase_to', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_conv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_id', sa.Integer(), nullable=True),
    sa.Column('phrase_from', sa.String(length=64), nullable=False),
    sa.Column('phrase_to', sa.String(length=64), nullable=False),
    sa.Column('convertation', sa.Float(), nullable=True),
    sa.Column('can_be_word', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_conv')
    op.drop_table('phrase_conv')
    op.drop_table('image_conv')
    with op.batch_alter_table('fandom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fandom_name'))

    op.drop_table('fandom')
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_ident'))

    op.drop_table('thread')
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setting_public'))
        batch_op.drop_index(batch_op.f('ix_setting_name'))

    op.drop_table('setting')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_last_entry'))

    op.drop_table('user')
    # ### end Alembic commands ###
